import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import getRandomPassedMatches from "@/actions/getRandomPassedMatches";
import Upcoming from "@/components/Home/Upcoming";
import Hero from "@/components/Home/Hero";
import Header from "@/components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const allData= await getRandomPassedMatches();


  return (
    <html lang="en">
      <body className={inter.className}>
   


        
        {children}
        <div className="flex flex-col w-full">

        <Header/>
        <Hero/>
        <Upcoming data={allData}/>
        </div>
        
        
        </body>
    </html>
  );
}
