import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/Header/Header";
import getAllLeagues from "@/actions/getAllLeagues";
import MobileFooter from "@/components/Footer/MobileFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const leagues = await getAllLeagues();
  // console.log("all of out leaguessssssssssssss",leagues);

  return (
    <html lang="en">
      <body className={inter.className}>

        <Header />

        {children}
        <MobileFooter />
      </body>
    </html>
  );
}